"""Master package spec + design language for the F1 concept car.

THIS FILE IS THE CONTRACT. Every part module reads its dimensions and its
surface vocabulary from here. Do not hard-code a number in a part module that
belongs in this file, and do not edit this file from a part module's task —
changing a shared datum silently moves somebody else's part.

--------------------------------------------------------------------------
COORDINATE SYSTEM
--------------------------------------------------------------------------
Units: millimetres. Right-handed.

    +X  forward   (toward the nose)
    +Y  left      (driver's left)
    +Z  up

    ORIGIN = ground plane, car centreline, FRONT AXLE.

So the front axle is x = 0, the rear axle is x = -3600, the ground is z = 0,
and the car is mirror-symmetric about the y = 0 plane. Every part module
builds in these car coordinates directly (no part-local frames) so the
assembly is a flat list of correctly-placed children and the animation sidecar
can rotate things about real, stated pivots.

--------------------------------------------------------------------------
DESIGN LANGUAGE  (the aesthetic rubric, expressed as rules)
--------------------------------------------------------------------------
The car is one idea repeated at five scales. Obey these or the car stops
reading as a single object:

1.  ONE SECTION FAMILY. Every aerodynamic element — front wing elements, beam
    wing, rear wing, floor fences, brake-duct vanes, diveplanes — is a lofted
    airfoil from `surfaces.airfoil_face()`. Nothing aerodynamic is a swept
    rectangle. Trailing edges close to `TE_THICKNESS` (1.2 mm) and never more.

2.  ONE BLADE SECTION. Every structural member in the airstream — wishbones,
    pushrods, track rods, wing pillars, mirror stalks, the rear wing pylon —
    is a lofted teardrop from `surfaces.blade_face()`, tapering along its length,
    with its long axis aligned to local flow (i.e. to X). Nothing structural
    is a plain cylinder where it can be seen.

3.  ONE TIP TREATMENT. Wherever an aero element ends outboard, it rolls over
    with radius `TIP_ROLL_R` into the surface it meets. Wing tips, endplate
    top edges, floor edges, diffuser side exits all share that radius family.

4.  ONE FEATURE-LINE RULE. A feature line either runs into another line, dies
    into a panel break, or wraps around an edge. It never fades out in the
    middle of a surface. The `SHOULDER_LINE` below is the car's primary
    feature line and every module that touches it must hand it off.

5.  RHYTHM. Multi-element cascades use the geometric progressions defined
    below (`CHORD_RATIO`, `GAP_RATIO`) — chord shrinks, gap tightens, and
    incidence steps up by a smoothly growing delta. Never arbitrary.

6.  RESTRAINT. Three material families only: carbon (near-black, most of the
    car), exposed metal (titanium / anodized / heat-tinted), and ONE accent —
    `ACCENT` vermillion — used as a thin edge stripe, a machined ring, or a
    single small jewel-like body. If in doubt, use less accent.

7.  DELICACY. Suspension and linkage members read as highly stressed and thin.
    Nothing in the airstream is chunky. Root-to-tip taper is mandatory.
"""

from __future__ import annotations

import math

from cadgen import build123d as bd

# ==========================================================================
# PACKAGE — overall vehicle
# ==========================================================================

WHEELBASE = 3600.0
FRONT_AXLE_X = 0.0
REAR_AXLE_X = -WHEELBASE

OVERALL_LENGTH = 5600.0
OVERALL_WIDTH = 2000.0
HALF_WIDTH = OVERALL_WIDTH / 2.0
OVERALL_HEIGHT = 950.0  # roll-hoop crown

NOSE_TIP_X = 1420.0  # forwardmost bodywork
REAR_MOST_X = -4180.0  # rear wing trailing edge (5600 total)

# ==========================================================================
# WHEELS & TIRES — 18" rims, visibly different front/rear section widths
# ==========================================================================

RIM_DIAMETER = 457.2  # 18"
TIRE_OD = 720.0
TIRE_R = TIRE_OD / 2.0
HUB_Z = TIRE_R  # 360 — axle height, both ends

TIRE_W_FRONT = 305.0
TIRE_W_REAR = 405.0

FRONT_TRACK = 1670.0  # hub-centre to hub-centre
REAR_TRACK = 1560.0
FRONT_HUB_Y = FRONT_TRACK / 2.0  # 835
REAR_HUB_Y = REAR_TRACK / 2.0  # 780

# outermost rubber: front 987.5, rear 982.5 — both inside HALF_WIDTH
FRONT_TIRE_OUTER_Y = FRONT_HUB_Y + TIRE_W_FRONT / 2.0
REAR_TIRE_OUTER_Y = REAR_HUB_Y + TIRE_W_REAR / 2.0
FRONT_TIRE_INNER_Y = FRONT_HUB_Y - TIRE_W_FRONT / 2.0
REAR_TIRE_INNER_Y = REAR_HUB_Y - TIRE_W_REAR / 2.0

# ==========================================================================
# FLOOR / RIDE HEIGHT — the car sits with rake, nose down is WRONG for
# ground effect: the floor is low at the front and lifts to the diffuser exit.
# ==========================================================================

FLOOR_Z_FRONT = 48.0  # underside of the floor at the leading edge
FLOOR_Z_REAR = 96.0  # underside at the rear axle line
FLOOR_LE_X = 780.0  # floor leading edge (behind the front wheel line)
FLOOR_TE_X = REAR_AXLE_X - 220.0  # -3820, diffuser exit plane
FLOOR_HALF_W = 900.0  # widest floor half-width, at the sidepod
PLANK_W = 300.0
PLANK_T = 10.0

DIFFUSER_START_X = REAR_AXLE_X + 480.0  # -3120, where the ramp kicks up
DIFFUSER_EXIT_Z = 385.0  # top of the diffuser exit at the centreline


def floor_z(x: float) -> float:
    """Underside height of the flat floor at station x (before the ramp)."""
    t = (FLOOR_LE_X - x) / (FLOOR_LE_X - REAR_AXLE_X)
    t = min(max(t, 0.0), 1.0)
    return FLOOR_Z_FRONT + (FLOOR_Z_REAR - FLOOR_Z_FRONT) * t


# ==========================================================================
# SURVIVAL CELL / COCKPIT
# ==========================================================================

BULKHEAD_FRONT_X = 700.0  # front bulkhead — nose bolts here
COCKPIT_OPENING_FRONT_X = -530.0
COCKPIT_OPENING_REAR_X = -1420.0
SURVIVAL_CELL_REAR_X = -1980.0  # engine mounting face
ROLL_HOOP_X = -1700.0
ROLL_HOOP_TOP_Z = OVERALL_HEIGHT  # 950
AIRBOX_MOUTH_X = -1620.0
COCKPIT_RIM_Z = 700.0  # cockpit side rim at its highest
HALO_FRONT_X = -420.0  # halo front strut root
CHASSIS_MAX_HALF_W = 400.0  # widest point of the survival cell

# ==========================================================================
# POWER UNIT / DRIVETRAIN
# ==========================================================================

ENGINE_FRONT_X = SURVIVAL_CELL_REAR_X  # -1980
ENGINE_REAR_X = -2880.0
CRANK_Z = 220.0  # crankshaft centreline
VEE_ANGLE_DEG = 90.0
GEARBOX_FRONT_X = ENGINE_REAR_X
GEARBOX_REAR_X = -3560.0
CRASH_STRUCTURE_REAR_X = -3980.0

# ==========================================================================
# AERO — FRONT WING
# ==========================================================================

FW_LE_X = 1450.0  # mainplane leading edge at centreline
FW_HALF_SPAN = 985.0  # endplate inner face
FW_ELEMENTS = 5  # mainplane + 4 flaps
FW_ROOT_CHORD = 300.0
CHORD_RATIO = 0.80  # element-to-element chord progression
GAP_RATIO = 0.90  # element-to-element slot gap progression
FW_ROOT_GAP = 15.0
# incidence deltas grow smoothly: 10, 10, 11, 12 degrees.
# Positive = trailing edge up = downforce (all wings here are inverted).
FW_INCIDENCE_DEG = (4.0, 14.0, 24.0, 35.0, 47.0)
FW_Z_ROOT = 78.0  # mainplane LE height on the centreline
FW_Z_TIP = 132.0  # mainplane LE height at the endplate
FW_ENDPLATE_TOP_Z = 300.0

# ==========================================================================
# AERO — REAR WING
# ==========================================================================

RW_HALF_SPAN = 520.0
RW_MAIN_LE_X = -3860.0
RW_MAIN_CHORD = 250.0
RW_MAIN_Z = 830.0  # mainplane leading-edge height
RW_MAIN_INCIDENCE_DEG = 14.0
RW_FLAP_CHORD = 165.0
RW_FLAP_INCIDENCE_CLOSED_DEG = 34.0
RW_FLAP_INCIDENCE_OPEN_DEG = -30.0  # DRS fully open (flap laid flat)
RW_TOP_Z = 948.0
# DRS pivot: on the flap's lower-front nose radius, visible from outside.
RW_DRS_PIVOT_X = -3985.0
RW_DRS_PIVOT_Z = 872.0
BEAM_WING_X = -3960.0
BEAM_WING_Z = 372.0
BEAM_WING_HALF_SPAN = 425.0
BEAM_WING_CHORD = 175.0

# ==========================================================================
# SUSPENSION HARDPOINTS — the single source of truth
#
# Stated for the LEFT (+Y) side; the right side is the y-mirror. Every
# suspension member, the uprights, the steering rack and the animation sidecar
# read these, so a member never "nearly" reaches its joint.
#
# The two front ball joints DEFINE the steering axis. The upright, brake, hub
# and wheel rotate about that axis; the wishbones do not move, because their
# outboard ends sit exactly on it. That is why steering does not disturb the
# pushrods or rockers — it is the real geometry, not a simplification.
# ==========================================================================

# --- front, outboard -------------------------------------------------------
F_LOWER_BALL = (6.0, 762.0, 166.0)
F_UPPER_BALL = (-10.0, 742.0, 548.0)
F_TRACKROD_OUT = (152.0, 736.0, 512.0)  # steering arm ball, ahead of the axis
F_PUSHROD_OUT = (12.0, 704.0, 184.0)  # on the lower wishbone, NOT the upright

# --- front, inboard --------------------------------------------------------
F_LOWER_IN_FWD = (332.0, 262.0, 126.0)
F_LOWER_IN_AFT = (-302.0, 288.0, 138.0)
F_UPPER_IN_FWD = (300.0, 256.0, 352.0)
F_UPPER_IN_AFT = (-330.0, 284.0, 374.0)
F_PUSHROD_IN = (256.0, 186.0, 508.0)  # rocker outer pivot
F_ROCKER_PIVOT = (300.0, 150.0, 462.0)  # rocker bearing centre
F_ROCKER_AXIS = (1.0, 0.06, 0.0)  # rocker rotates about ~X
F_DAMPER_IN = (392.0, 66.0, 566.0)
F_DAMPER_OUT = (176.0, 118.0, 556.0)
F_TORSION_BAR = (300.0, 150.0, 462.0)  # coaxial with the rocker bearing
F_ARB_Z = 596.0
F_RACK_X = 152.0
F_RACK_Z = 505.0
F_RACK_END = (152.0, 318.0, 505.0)  # inner track-rod ball, rack at centre
F_RACK_TRAVEL = 62.0  # +/- mm of rack shift at full lock

MAX_STEER_DEG = 20.0  # road-wheel angle at full lock

# --- rear, outboard --------------------------------------------------------
R_LOWER_BALL = (-3600.0, 706.0, 158.0)
R_UPPER_BALL = (-3600.0, 694.0, 540.0)
R_TOELINK_OUT = (-3760.0, 700.0, 196.0)
R_PULLROD_OUT = (-3608.0, 676.0, 534.0)

# --- rear, inboard ---------------------------------------------------------
R_LOWER_IN_FWD = (-3300.0, 250.0, 176.0)
R_LOWER_IN_AFT = (-3830.0, 236.0, 190.0)
R_UPPER_IN_FWD = (-3286.0, 240.0, 396.0)
R_UPPER_IN_AFT = (-3818.0, 224.0, 404.0)
R_TOELINK_IN = (-3846.0, 232.0, 214.0)
R_PULLROD_IN = (-3312.0, 214.0, 214.0)  # rocker outer pivot, low in the box
R_ROCKER_PIVOT = (-3272.0, 158.0, 268.0)
R_ROCKER_AXIS = (1.0, -0.05, 0.0)
R_DAMPER_IN = (-3120.0, 60.0, 300.0)
R_DAMPER_OUT = (-3300.0, 132.0, 314.0)
R_ARB_Z = 356.0

# ==========================================================================
# DRS MECHANISM — a visible four-bar, not a hidden box
#
# The flap rotates about DRS_PIVOT (an axis along Y). A machined bellcrank on
# the inner face of each endplate swings about DRS_CRANK_PIVOT and drives a
# polished link to a lug on the flap's underside. The link length is DERIVED
# from the closed pose so the four-bar closes exactly at every DRS value.
# ==========================================================================

DRS_PIVOT = (RW_DRS_PIVOT_X, 0.0, RW_DRS_PIVOT_Z)
DRS_CRANK_PIVOT = (-3894.0, 462.0, 800.0)
DRS_CRANK_R = 66.0
DRS_CRANK_ANGLE_CLOSED_DEG = 118.0  # crank arm direction when DRS is shut
DRS_LUG_R = 88.0  # flap lug radius from the flap pivot
DRS_LUG_ANGLE_CLOSED_DEG = 214.0  # lug direction from the pivot when shut
DRS_LINK_Y = 462.0  # the linkage plane, just inboard of the endplate


def _drs_point(center, radius: float, angle_deg: float):
    a = math.radians(angle_deg)
    return (
        center[0] + radius * math.cos(a),
        DRS_LINK_Y,
        center[2] + radius * math.sin(a),
    )


DRS_CRANK_END_CLOSED = _drs_point(
    DRS_CRANK_PIVOT, DRS_CRANK_R, DRS_CRANK_ANGLE_CLOSED_DEG
)
DRS_LUG_CLOSED = _drs_point(DRS_PIVOT, DRS_LUG_R, DRS_LUG_ANGLE_CLOSED_DEG)
DRS_LINK_L = math.dist(DRS_CRANK_END_CLOSED, DRS_LUG_CLOSED)

# ==========================================================================
# SURFACE VOCABULARY — shared geometric constants
# ==========================================================================

TE_THICKNESS = 1.2  # every aero trailing edge closes to this, never more
TIP_ROLL_R = 9.0  # the one tip-roll radius family
PANEL_GAP = 3.0  # visible gap at every bodywork panel break
SKIN_T = 4.0  # carbon skin thickness where a panel edge is visible
BLADE_MIN_T = 7.0  # thinnest structural blade section
FILLET_LADDER = (8.0, 5.0, 3.0, 1.5, 0.8)  # try radii in order, keep first win

# The car's primary feature line: a single shoulder crease that starts on the
# nose flank, sweeps through the sidepod inlet upper lip, runs along the top
# of the undercut and dies into the rear-wing pylon root. Any module the line
# passes through must start and end it at these stations so it hands off.
SHOULDER_LINE = (
    (1180.0, 118.0, 232.0),  # nose flank
    # The nose/tub panel break at x=700 is the tightest hand-off on the car.
    # This point pins the crease to the agreed bulkhead section half-width
    # (194.6 as delivered by the nose) so the line does not step 30 mm
    # outboard across the joint; the next point was pulled in to match so the
    # run aft of the bulkhead stays a gentle taper rather than a kink.
    (700.0, 195.0, 266.0),  # nose <-> survival cell panel break
    (620.0, 205.0, 268.0),  # front bulkhead shoulder
    (-180.0, 336.0, 300.0),  # cockpit side, ahead of the driver
    (-980.0, 452.0, 348.0),  # sidepod inlet upper lip
    (-1780.0, 500.0, 396.0),  # sidepod crest
    (-2620.0, 372.0, 404.0),  # engine cover flank
    (-3320.0, 176.0, 392.0),  # coke-bottle waist
    (-3800.0, 62.0, 386.0),  # pylon root
)

# ==========================================================================
# MATERIAL PALETTE — RED bodywork over carbon, exposed metal, ONE accent
#
# The car is red. It is NOT red everywhere, and that is deliberate: on a real
# red car the painted skin is red while the aerodynamic and structural carbon
# stays black, and the contrast between the two is most of why it looks
# expensive. So the split is:
#
#   CARBON_GLOSS  the painted OUTER SKIN -> RED. Nose, survival cell, sidepod
#                 panels, engine cover, airbox, floor top, wheel covers.
#   CARBON        structural + aero elements -> stays near-black. Wing
#                 elements, endplates, halo shroud, internals. Black wings
#                 against a red body is the classic read.
#   CARBON_MATTE  underfloor, inner ducts, tunnel roofs -> stays near-black.
#   CARBON_WEAVE  exposed twill flanges and the plank -> stays dark, warmed a
#                 touch so it sits between the red and the black.
#
# Value discipline still applies: the red is DEEP, not signal-bright. The
# stage runs saturation 1.10 and contrast 1.28, so a pure 0.8-red blows out to
# orange in the key and loses every crease. Keeping the base dark lets the
# highlight do the work and keeps the shoulder line readable.
# ==========================================================================

# Plain RGB(A) tuples / sRGB hex strings, not bd.Color objects: build123d's
# Shape.color setter builds the Color on assignment, and a module-level
# bd.Color(...) would import the CAD kernel before the @step freshness gate.
RED = (0.520, 0.043, 0.038)  # the bodywork red — deep, slightly warm
RED_DEEP = (0.240, 0.022, 0.020)  # shadowed / inner face of a red panel

CARBON = (0.072, 0.078, 0.088)  # primary structural carbon, near black
CARBON_GLOSS = RED  # painted outer bodywork skin — SEE ABOVE
CARBON_WEAVE = (0.118, 0.108, 0.106)  # exposed twill, warmed toward the red
CARBON_MATTE = (0.088, 0.090, 0.096)  # matte underfloor / inner surfaces

# Exposed metal is deliberately GUNMETAL, not bright. At 0.56/0.70 the
# suspension and halo were the brightest objects in every view and pulled the
# eye straight off the bodywork — the car read as a white linkage diagram
# wearing a black shell. Real machined titanium under studio light is much
# darker than intuition suggests. Keep metals below the accent in value.
TITANIUM = (0.395, 0.408, 0.430)  # machined uprights, wishbone tips
ALLOY = (0.545, 0.558, 0.578)  # bright machined aluminium
ANODIZED = (0.235, 0.255, 0.285)  # dark anodized brackets and clevises
INCONEL = (0.318, 0.278, 0.238)  # heat-tinted exhaust / turbine
MAGNESIUM = (0.400, 0.398, 0.386)  # cast gearbox / engine block
STEEL = (0.470, 0.480, 0.500)  # fasteners, Dzus, pins
COPPER = (0.520, 0.330, 0.205)  # coolers, bus bars
GOLD_FOIL = (0.640, 0.520, 0.255)  # heat-shield foil, sparingly

# The accent was vermillion when the body was black. On a red car vermillion
# goes muddy — two reds a few steps apart read as a printing error, not a
# stripe. A warm chalk white is the classic answer: it reads crisply on the
# red skin AND on the black carbon, so the same accent still ties the whole
# car together, which was the point of having exactly one.
ACCENT = (0.910, 0.892, 0.862)  # warm chalk white — THE accent
ACCENT_DEEP = (0.560, 0.545, 0.520)  # shadowed side of the accent

RUBBER = (0.052, 0.052, 0.056)  # slick tread
RUBBER_SIDEWALL = (0.068, 0.068, 0.072)
CARBON_DISC = (0.140, 0.132, 0.126)  # carbon brake disc
GLASS = (0.030, 0.055, 0.090)  # mirror glass, camera lenses
SEAT = (0.078, 0.080, 0.086)
BELT = (0.120, 0.122, 0.130)

# ==========================================================================
# DERIVED CASCADE HELPERS
# ==========================================================================


def cascade_chords(root_chord: float, n: int, ratio: float = CHORD_RATIO):
    """Geometric chord progression for an n-element cascade."""
    return [root_chord * ratio**i for i in range(n)]


def cascade_gaps(root_gap: float, n: int, ratio: float = GAP_RATIO):
    """Geometric slot-gap progression between n elements (n-1 gaps)."""
    return [root_gap * ratio**i for i in range(max(n - 1, 0))]


def lerp(a: float, b: float, t: float) -> float:
    return a + (b - a) * t


def smoothstep(t: float) -> float:
    t = min(max(t, 0.0), 1.0)
    return t * t * (3.0 - 2.0 * t)


def shoulder_at(x: float):
    """Sample the primary feature line at station x -> (y, z).

    Modules that carry the shoulder line call this so the crease is continuous
    across panel breaks instead of each module inventing its own path.
    """
    pts = SHOULDER_LINE
    if x >= pts[0][0]:
        return pts[0][1], pts[0][2]
    if x <= pts[-1][0]:
        return pts[-1][1], pts[-1][2]
    for i in range(len(pts) - 1):
        x0, y0, z0 = pts[i]
        x1, y1, z1 = pts[i + 1]
        if x1 <= x <= x0:
            t = smoothstep((x0 - x) / (x0 - x1))
            return lerp(y0, y1, t), lerp(z0, z1, t)
    return pts[-1][1], pts[-1][2]


def deg(a: float) -> float:
    return a * math.pi / 180.0
