//! STEP (ISO 10303-21) tessellation.
//!
//! STEP files usually describe solids as boundary representations — trimmed
//! analytic and NURBS surfaces — so there are no triangles to read out. Each
//! shell is evaluated and meshed, then flattened into the same triangle soup
//! the STL path produces, which lets the rest of the pipeline stay unaware of
//! STEP. AP242 also allows a file to ship its mesh directly, which is handled
//! by [`tessellated`].

pub mod circular_arc;
pub mod cone;
pub mod cylinder;
pub mod lattice;
pub mod meshing_policy;
pub mod part21;
pub mod policy_geometry;
pub mod spline_carrier;
mod tessellated;
pub mod torus_deck;

use std::collections::BTreeMap;
use std::time::Instant;

use rayon::prelude::*;
use truck_meshalgo::prelude::*;
use truck_meshalgo::tessellation::{TessellationFailureReason, TorusAnnulusAttempt};
use truck_stepio::r#in::Table;
use truck_topology::compress::FaceProvenance;

use crate::timing::Timings;

/// Tolerance for a model with no measurable extent, where there is nothing to
/// scale against. Nothing renders from such a shell anyway; this only keeps a
/// degenerate bounding box from producing a zero or non-finite tolerance.
const DEGENERATE_TOLERANCE: f64 = 1.0e-3;

/// Chord deviation as a fraction of a shell's diagonal. Scaling to the model
/// keeps output density stable across files that use different units.
#[allow(dead_code)]
const RELATIVE_TOLERANCE: f64 = 0.001;

/// How many points to sample along each edge when measuring the model.
///
/// Enough to catch the mid-span bulge of a circle or a spline, which is where
/// a vertex-only box loses the most; more would not change the diameter.
const EDGE_SAMPLES: u32 = 4;

/// truck panics below this, and it is not a tolerance we could honour anyway.
///
/// This is not the millimetre-scale floor the comment on [`model_tolerance`]
/// argues against: it is the hard minimum truck's own division asserts on. A
/// model whose measured extent is tiny — or an isolated shell pulled out of a
/// larger assembly — otherwise computes a tolerance below it and aborts.
const MINIMUM_TOLERANCE: f64 = 1.0e-6;

/// How many lost-face identities one shell contributes to the report.
///
/// Per-shell rather than global so a model whose loss is spread thinly still
/// names faces from several shells instead of exhausting the budget on the
/// first one that fails.
const LOST_FACE_IDS_PER_SHELL: usize = 4;

/// How many lost-face identities the warning prints in total.
///
/// A diagnostic that floods stderr gets piped to `/dev/null`, and then it
/// diagnoses nothing. The count is always exact; only the naming is capped.
const LOST_FACE_IDS_REPORTED: usize = 12;

/// Tessellate every shell in a STEP file into one indexed triangle mesh.
///
/// Positions carry no shared topology between faces, so each triangle brings
/// its own vertices and normals are generated by the caller.
pub fn parse_step(
    bytes: &[u8],
    timings: &mut Timings,
) -> anyhow::Result<(Vec<[f32; 3]>, Vec<u32>)> {
    let text = std::str::from_utf8(bytes)
        .map(std::borrow::Cow::Borrowed)
        // STEP is nominally ASCII, but exporters emit Latin-1 in comments and
        // names often enough that rejecting the file would be unhelpful.
        .unwrap_or_else(|_| bytes.iter().map(|&b| b as char).collect::<String>().into());

    let parse_started = Instant::now();
    let mut exchange = read_exchange(&text)?;
    timings.record("step_parse", parse_started.elapsed());

    if exchange.data.is_empty() {
        anyhow::bail!("STEP file contains no data section");
    }
    let section = exchange.data.swap_remove(0);

    // Hand the syntax tree over rather than lending it. The tree is roughly
    // eight times the size of the file and the table another three, so
    // building the table from a borrowed tree keeps both fully resident and
    // makes peak memory, not speed, the limit on how large a model will load.
    let table_started = Instant::now();
    let table = Table::from_owned_data_section(section);
    timings.record("step_table", table_started.elapsed());

    // The source-declared spline-axis closure of every spline surface entity,
    // read from the STEP table before conversion erases it. Keyed by surface
    // entity id, the same id `FaceProvenance.surface_id` carries per face, so
    // `wrap_shell_with_closure` can attach it to each face's `PolicySurface`.
    let closure_map = lattice::spline_closure_map(&table);

    if table.shell.is_empty() {
        // AP242 lets a file ship its mesh directly instead of a boundary
        // representation, in which case there is nothing to evaluate and the
        // triangles are read straight out of the syntax tree. That tree was
        // consumed above, which is the right trade for the boundary
        // representations that are almost every file; these have to read it
        // again. They are rare and small, and parsing is no longer the
        // expensive part of loading one.
        let tessellated_started = Instant::now();
        let reread = read_exchange(&text)?;
        let tessellated = reread.data.first().and_then(tessellated::read);
        timings.record("step_tessellated_read", tessellated_started.elapsed());
        if let Some((positions, indices)) = tessellated {
            return Ok((positions, indices));
        }
        anyhow::bail!("STEP file contains no shells or tessellated faces");
    }

    // Resolve the entity graph first. Tolerance is derived from the whole
    // model rather than per shell: a shell-local tolerance meshes a part split
    // into many small shells far finer than the same part as one shell, and a
    // degenerate shell has no extent to scale by at all.
    let mesh_started = Instant::now();
    let shells = table
        .shell
        .par_iter()
        .map(|(id, shell)| {
            // The declared count is read from the source holder, before
            // conversion, because conversion is allowed to drop a face and
            // nothing downstream can tell that it did.
            let declared = shell.cfs_faces.len();
            table
                .to_compressed_shell(*id, shell)
                .map(|compressed| (declared, compressed))
                .map_err(|error| format!("shell #{id}: {error}"))
        })
        .collect::<Vec<_>>();

    let mut model = BoundingBox::<Point3>::new();
    for (_, shell) in shells.iter().flatten() {
        for vertex in &shell.vertices {
            model.push(*vertex);
        }
        // Vertices alone understate the model, often badly. A full circle
        // carries a single topological vertex, so a disc or a cylinder adds
        // almost nothing to the box while occupying real space: a washer whose
        // three vertices span 0.2 mm measured as 0.2 mm across, and the whole
        // submarine model measured 3.06 against rendered bounds of 7.33.
        // Since the tolerance is a fraction of this diameter, understating it
        // meshes every model finer than asked. Sampling each edge closes the
        // gap for the cost of a few curve evaluations per edge.
        for edge in &shell.edges {
            let (start, end) = edge.curve.range_tuple();
            for step in 0..=EDGE_SAMPLES {
                let t = start + (end - start) * f64::from(step) / f64::from(EDGE_SAMPLES);
                model.push(edge.curve.subs(t));
            }
        }
    }
    let tolerance = model_tolerance(model.diameter());
    // The targeted linear-plus-angular meshing policy. The scalar `tolerance`
    // remains the geometric-error bound Truck receives; the policy's angular
    // floor is applied per feature by `policy_geometry`'s wrappers, which
    // override only `parameter_division` and delegate everything else to
    // Truck unchanged. See `step/meshing_policy.rs`.
    let policy = meshing_policy::MeshingPolicy::DEFAULT;

    // Shells are independent, so tessellation parallelizes cleanly. A shell
    // that fails is reported rather than silently dropped, so a partial render
    // never passes for a complete one.
    let meshed = shells
        .into_par_iter()
        .map(|shell| {
            let (declared, shell) = shell?;
            // Only a shell with no faces carries nothing to render. Counting
            // *vertices* was wrong: a disc or a cylinder is bounded by full
            // circles, which have one topological vertex each, so this
            // discarded valid solids in silence. A 74-entity washer that OCCT
            // renders fine reached look as "tessellation produced no
            // triangles" for exactly this reason.
            if shell.faces.is_empty() {
                // Still report what the file declared. A shell whose faces all
                // failed to convert arrives here looking identical to a shell
                // that genuinely holds none.
                return Ok((
                    PolygonMesh::default(),
                    FaceTally {
                        declared,
                        ..FaceTally::default()
                    },
                    // Nothing survived to carry an identity: these faces were
                    // lost during conversion, before any face object existed.
                    Vec::new(),
                    // And nothing reached the tessellator, so it has no verdict
                    // to offer. An empty list here is not "no failures" — it is
                    // "this loss happened upstream of the stage that names
                    // reasons", which `unconverted()` already reports.
                    Vec::new(),
                    // No torus outcomes: nothing reached the tessellator.
                    BTreeMap::new(),
                ));
            }
            // Periodicity now reaches the tessellator as a descriptor built
            // from the concrete STEP representation, not as a bare accessor
            // result. See src/step/lattice.rs and REFINEMENT_AUDIT.md §6.
            //
            // G8: through the outcome-preserving entry point. The tessellator
            // builds a typed `TessellationFailure` for every face it refuses —
            // including `ContradictoryDualParity`, which is a *proved*
            // inconsistency — and the mesh-only entry point destroyed it one
            // line after constructing it. The reasons now arrive beside the
            // shell, so a face that produced nothing can say why rather than
            // being inferred from the shape of its absence.
            let outcome = policy_geometry::wrap_shell_with_closure(shell, policy, &closure_map)
                .robust_triangulation_with_torus_outcome(
                    tolerance,
                    |s: &policy_geometry::PolicySurface| {
                        lattice::lattice_of_with_closure(s.inner(), s.source_closure())
                    },
                    |s: &policy_geometry::PolicySurface| lattice::support_schema_of(s.inner()),
                    |c: &policy_geometry::PolicyCurve| lattice::curve_schema_of(c.inner()),
                    |s: &policy_geometry::PolicySurface| {
                        cylinder::identify_source_cylinder_opt(s.inner())
                    },
                    |c: &policy_geometry::PolicyCurve| lattice::cylinder_curve_schema_of(c.inner()),
                    |c: &policy_geometry::PolicyCurve| {
                        lattice::cylinder_curve_family_of(c.inner())
                    },
                    |s: &policy_geometry::PolicySurface| cone::identify_source_cone_opt(s.inner()),
                    |s: &policy_geometry::PolicySurface| {
                        torus_deck::identify_source_torus_opt(s.inner())
                    },
                );
            let meshed = outcome.shell;
            // A face that could not be meshed is dropped from the polygon
            // without comment, so count them here while the structure still
            // says which is which. Malformed geometry does reach this: a wire
            // that bounds nothing leaves its face untessellated.
            //
            // There are two ways to lose a face and they do not have the same
            // cause, so they are not summed. `None` is a surface that could not
            // be produced at all, which on real files is mostly a spline
            // failing to converge. `Some` holding no triangles is a surface
            // that meshed to nothing, which happens to *planes* — a separate
            // and unexplained defect. Counting only the first understated the
            // loss on 00009190 by 118 faces, 276 against 394.
            let mut tally = FaceTally {
                declared,
                total: meshed.faces.len(),
                ..FaceTally::default()
            };
            // The entity behind each loss, so the warning can name faces
            // instead of only counting them. Capped: a model that loses
            // thousands does not need thousands of ids on stderr to be
            // diagnosed, and the cap keeps this bounded on the worst input
            // rather than the typical one.
            let mut lost_ids = Vec::new();
            // Why each lost face was lost, by reason. This replaces inference
            // from the *shape* of the loss with the tessellator's own verdict;
            // the `unsurfaced`/`empty` split is kept beside it because the two
            // do not partition the same way — a face can be `Some(empty)` for
            // several distinct reasons.
            let mut reasons: Vec<TessellationFailureReason> = Vec::new();
            for (face, failure) in meshed.faces.iter().zip(&outcome.face_failures) {
                let lost = match &face.surface {
                    None => {
                        tally.unsurfaced += 1;
                        true
                    }
                    Some(mesh) if mesh.faces().is_empty() => {
                        tally.empty += 1;
                        true
                    }
                    Some(_) => false,
                };
                if let Some(failure) = failure {
                    reasons.push(failure.reason);
                }
                if lost && lost_ids.len() < LOST_FACE_IDS_PER_SHELL && !face.provenance.is_empty() {
                    lost_ids.push(face.provenance);
                }
            }
            // Torus observer: count the typed outcome of each face the torus
            // annulus route attempted. This runs in shadow (TRUCK_PROBE_TORUS)
            // or recovery (TRUCK_FORMAL_RECOVERY_TORUS) mode; in shadow the
            // mesh is not replaced, so the counts reproduce the corrected
            // census without changing production output.
            let mut torus_census: BTreeMap<&'static str, usize> = BTreeMap::new();
            for attempt in &outcome.torus_band_attempts {
                let tag = match attempt {
                    Some(TorusAnnulusAttempt::Recovered {
                        conformance, ..
                    }) => match conformance {
                        truck_meshalgo::tessellation::formal::ConformanceTag::SourceClean => {
                            "recovered_clean"
                        }
                        truck_meshalgo::tessellation::formal::ConformanceTag::MalformedTwoOuterBoundsOnCertifiedTorusAnnulus => {
                            "recovered_malformed"
                        }
                    },
                    Some(TorusAnnulusAttempt::Refused(exit)) => exit.tag(),
                    None => continue,
                };
                *torus_census.entry(tag).or_insert(0) += 1;
            }
            Ok::<_, String>((meshed.to_polygon(), tally, lost_ids, reasons, torus_census))
        })
        .collect::<Vec<_>>();
    timings.record("step_tessellate", mesh_started.elapsed());

    let mut positions = Vec::new();
    let mut indices = Vec::new();
    let mut failures = Vec::new();
    let mut faces = FaceTally::default();
    let mut lost_faces: Vec<FaceProvenance> = Vec::new();
    let mut reason_counts: BTreeMap<TessellationFailureReason, usize> = BTreeMap::new();
    let mut torus_census_total: BTreeMap<&'static str, usize> = BTreeMap::new();
    for result in meshed {
        match result {
            Ok((polygon, tally, lost_ids, reasons, torus_census)) => {
                append_polygon(&polygon, &mut positions, &mut indices);
                faces.declared += tally.declared;
                faces.total += tally.total;
                faces.unsurfaced += tally.unsurfaced;
                faces.empty += tally.empty;
                for reason in reasons {
                    *reason_counts.entry(reason).or_insert(0) += 1;
                }
                for (tag, count) in torus_census {
                    *torus_census_total.entry(tag).or_insert(0) += count;
                }
                if lost_faces.len() < LOST_FACE_IDS_REPORTED {
                    lost_faces.extend(lost_ids);
                }
            }
            Err(error) => failures.push(error),
        }
    }

    if positions.is_empty() {
        anyhow::bail!(
            "STEP tessellation produced no triangles{}",
            describe(&failures)
        );
    }
    if !failures.is_empty() {
        // Loud on stderr rather than a hard failure: a mostly-complete render
        // is useful, but the user must know it is incomplete.
        eprintln!(
            "warning: {} of {} STEP shells failed to tessellate{}",
            failures.len(),
            table.shell.len(),
            describe(&failures)
        );
    }
    if faces.lost() > 0 {
        // A shell can succeed while individual faces within it do not, and
        // those vanish from the mesh silently. Without this a model missing
        // geometry is indistinguishable from a complete one. The split is
        // reported because it points at which defect to chase.
        eprintln!(
            "warning: {} of {} STEP faces produced no geometry and are missing \
             from the render ({} failed to convert, {} had no surface, \
             {} meshed to nothing)",
            faces.lost(),
            faces.declared,
            faces.unconverted(),
            faces.unsurfaced,
            faces.empty
        );
        // G8: the tessellator's own reason for each refusal. Previously every
        // one of these arrived as an empty mesh and the cause had to be guessed
        // from which bucket the face fell into. Ordered by count so the largest
        // population names itself first.
        if !reason_counts.is_empty() {
            let mut by_size: Vec<_> = reason_counts.iter().collect();
            by_size.sort_by(|a, b| b.1.cmp(a.1).then(a.0.cmp(b.0)));
            let summary = by_size
                .iter()
                .map(|(reason, count)| format!("{reason:?} x{count}"))
                .collect::<Vec<_>>()
                .join(", ");
            eprintln!("         tessellation refused: {summary}");
        }
        // Naming even a few of them turns "geometry is missing somewhere" into
        // a place to start: every id here can be grepped straight out of the
        // source file, and the chain says which layer is meant.
        //
        // Only *tessellation-stage* losses can appear. A face lost during
        // conversion never became a face object, so nothing survives to carry
        // its provenance — which is why the count below is deliberately split
        // rather than presented as one total with a dozen examples. Saying "and
        // N more" over a mixed population would imply every unnamed face
        // reached the stage that could have named it.
        if !lost_faces.is_empty() {
            let named = faces.unsurfaced + faces.empty;
            let shown = lost_faces
                .iter()
                .take(LOST_FACE_IDS_REPORTED)
                .map(FaceProvenance::to_string)
                .collect::<Vec<_>>()
                .join("; ");
            let unnamed = named.saturating_sub(lost_faces.len().min(LOST_FACE_IDS_REPORTED));
            eprintln!("         of the {named} lost after conversion: {shown}");
            if unnamed > 0 {
                eprintln!("         and {unnamed} more not listed");
            }
            if faces.unconverted() > 0 {
                eprintln!(
                    "         the {} lost during conversion cannot be named yet \
                     — no face object exists to carry their provenance",
                    faces.unconverted()
                );
            }
        }
    }

    // Torus observer census: the typed outcome of every face the torus annulus
    // route attempted, across all shells. Printed unconditionally when the
    // torus probe or recovery gate is active, so the census can be confirmed
    // against the corrected expected counts.
    if !torus_census_total.is_empty() {
        let mut by_size: Vec<_> = torus_census_total.iter().collect();
        by_size.sort_by(|a, b| b.1.cmp(a.1).then(a.0.cmp(b.0)));
        let summary = by_size
            .iter()
            .map(|(tag, count)| format!("{tag}={count}"))
            .collect::<Vec<_>>()
            .join(", ");
        let total: usize = torus_census_total.values().sum();
        eprintln!("torus observer: {total} faces attempted, {summary}");
    }

    Ok((positions, indices))
}

/// How many faces a shell held, and how many of them yielded no mesh.
///
/// The three loss causes are kept apart because they are different bugs, and a
/// single "dropped" number hid that. See the counting site for which is which.
#[derive(Debug, Default, Clone, Copy)]
struct FaceTally {
    /// Faces the STEP file names on this shell, before any conversion.
    ///
    /// This is the only denominator that cannot move. `total` counts what
    /// survived the entity graph, so measuring loss against it lets a
    /// conversion that drops faces outright *improve* the reported ratio while
    /// deleting geometry — which is exactly what happened when bound conversion
    /// was made all-or-nothing: 274 faces left the model and the warning got
    /// quieter.
    declared: usize,
    total: usize,
    /// No surface could be produced for the face at all.
    unsurfaced: usize,
    /// A surface was produced, and it meshed to no triangles.
    empty: usize,
}

impl FaceTally {
    /// Faces the file declared that never reached tessellation at all.
    fn unconverted(&self) -> usize {
        self.declared.saturating_sub(self.total)
    }

    /// Faces that reach the render carrying no geometry, however they got there.
    fn lost(&self) -> usize {
        self.unconverted() + self.unsurfaced + self.empty
    }
}

/// Read the exchange structure.
///
/// [`part21`] reads it far faster than ruststep's nom grammar, but covers a
/// little less of the standard. Whatever it turns down is handed to ruststep,
/// so the fast reader can only add speed and never narrows what look accepts.
fn read_exchange(text: &str) -> anyhow::Result<ruststep::ast::Exchange> {
    match part21::parse(text) {
        Ok(exchange) => Ok(exchange),
        Err(_) => ruststep::parser::parse(text)
            .map_err(|error| anyhow::anyhow!("failed to parse STEP: {error}")),
    }
}

/// Scale the chord tolerance to the model so that a millimetre part and a
/// metre part mesh to comparable density.
///
/// This deliberately has no absolute floor. It used to be held at 1e-3 to stay
/// clear of truck's own 1e-6 minimum, since curves are tessellated in their own
/// parameter space and a placement scales the tolerance down by its radius
/// before that check happens. But an absolute floor silently assumes the file
/// is measured in millimetres. The NIST corpus is, uniformly, so the assumption
/// held there and nowhere else: an Onshape export in metres puts a half
/// millimetre fillet at a radius of 0.0005, well under a 1e-3 floor, which both
/// meshed the part absurdly coarsely and asked truck to approximate a feature
/// to worse than its own size.
///
/// The headroom the floor provided is already in the relative term. Against a
/// radius bounded by the model, `diameter * 1e-3` sits three orders of
/// magnitude above `diameter * 1e-6`, which is the same margin the floor was
/// chosen to give — only expressed in the units the file actually uses.
fn model_tolerance(diameter: f64) -> f64 {
    // The linear deflection comes from the meshing policy so a policy edit is
    // the single source of truth for the geometric-error bound (and so the
    // cache identity, which keys on the policy, actually tracks it).
    let scaled = diameter * meshing_policy::MeshingPolicy::DEFAULT.relative_linear_deflection;
    if scaled.is_finite() && scaled > 0.0 {
        scaled.max(MINIMUM_TOLERANCE)
    } else {
        DEGENERATE_TOLERANCE
    }
}

/// Flatten a meshed shell, dropping the per-face indexing in favour of one
/// flat vertex buffer. Triangles are emitted unwelded so that creased edges
/// keep their own normals when the caller generates them.
fn append_polygon(polygon: &PolygonMesh, positions: &mut Vec<[f32; 3]>, indices: &mut Vec<u32>) {
    let vertices = polygon.positions();
    // The triangle count is known, and these buffers reach tens of megabytes
    // on a large assembly. Growing them by doubling holds the old and the new
    // allocation at once at every step, so the high-water mark ends up well
    // above what the mesh actually needs.
    let incoming = polygon.tri_faces().len() * 3;
    positions.reserve(incoming);
    indices.reserve(incoming);
    for face in polygon.tri_faces() {
        for vertex in face {
            let point = vertices[vertex.pos];
            indices.push(positions.len() as u32);
            positions.push([point.x as f32, point.y as f32, point.z as f32]);
        }
    }
}

fn describe(failures: &[String]) -> String {
    match failures.first() {
        Some(first) if failures.len() == 1 => format!(": {first}"),
        Some(first) => format!(": {first} (and {} more)", failures.len() - 1),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A metre-scale export is the case an absolute floor got wrong. Onshape
    /// writes `SI_UNIT($, .METRE.)`, so a part 100 mm across has a diameter of
    /// 0.1 and its half-millimetre fillets have a radius of 0.0005. The old
    /// 1e-3 floor exceeded both the model's own relative tolerance and those
    /// radii, which meshed the part far too coarsely and asked truck to
    /// approximate a sphere to worse than its own size.
    #[test]
    fn a_metre_scale_model_is_not_held_to_a_millimetre_floor() {
        let tolerance = model_tolerance(0.1);
        assert!(
            tolerance < 0.0005,
            "tolerance {tolerance} must stay under a half-millimetre feature"
        );
        assert_eq!(tolerance, 0.1 * RELATIVE_TOLERANCE);
    }

    /// The millimetre-scale corpus this was originally tuned against must mesh
    /// exactly as it did before, since its tolerance was always the scaled term
    /// rather than the floor.
    #[test]
    fn a_millimetre_scale_model_is_unchanged() {
        assert_eq!(model_tolerance(200.0), 0.2);
        assert_eq!(model_tolerance(6.0), 0.006);
    }

    /// Tolerance has to keep tracking the model across every unit a CAD system
    /// might write, rather than flattening onto a constant at small scales.
    #[test]
    fn tolerance_tracks_the_model_across_unit_scales() {
        for diameter in [1.0e-3, 1.0, 1.0e3, 1.0e6] {
            assert_eq!(model_tolerance(diameter), diameter * RELATIVE_TOLERANCE);
        }
    }

    /// A shell with no extent has nothing to scale against, and must not yield
    /// a zero or non-finite tolerance for truck to divide by.
    #[test]
    fn a_degenerate_model_falls_back_to_a_usable_tolerance() {
        for diameter in [0.0, -1.0, f64::NAN, f64::INFINITY] {
            let tolerance = model_tolerance(diameter);
            assert!(
                tolerance.is_finite() && tolerance > 0.0,
                "diameter {diameter} produced tolerance {tolerance}"
            );
        }
    }
}
