//! STEP (ISO 10303-21) tessellation.
//!
//! STEP files describe solids as boundary representations — trimmed analytic
//! and NURBS surfaces — so there are no triangles to read out. Each shell is
//! evaluated and meshed, then flattened into the same triangle soup the STL
//! path produces, which lets the rest of the pipeline stay unaware of STEP.

use std::time::Instant;

use anyhow::Context;
use rayon::prelude::*;
use truck_meshalgo::prelude::*;
use truck_stepio::r#in::Table;

use crate::timing::Timings;

/// Floor for the adaptive tolerance. truck asserts at 1e-6, and divides the
/// tolerance by a placement's scale before checking, so this keeps three
/// orders of magnitude of headroom for large-radius geometry.
const MIN_TOLERANCE: f64 = 1.0e-3;

/// Chord deviation as a fraction of a shell's diagonal. Scaling to the model
/// keeps output density stable across files that use different units.
const RELATIVE_TOLERANCE: f64 = 0.001;

/// Tessellate every shell in a STEP file into one indexed triangle mesh.
///
/// Positions carry no shared topology between faces, so each triangle brings
/// its own vertices and normals are generated by the caller.
pub fn parse_step(
    bytes: &[u8],
    timings: &mut Timings,
) -> anyhow::Result<(Vec<[f32; 3]>, Vec<u32>)> {
    let text = std::str::from_utf8(bytes)
        .map(std::borrow::Cow::Borrowed)
        // STEP is nominally ASCII, but exporters emit Latin-1 in comments and
        // names often enough that rejecting the file would be unhelpful.
        .unwrap_or_else(|_| bytes.iter().map(|&b| b as char).collect::<String>().into());

    let parse_started = Instant::now();
    let exchange = ruststep::parser::parse(&text)
        .map_err(|error| anyhow::anyhow!("failed to parse STEP: {error}"))?;
    timings.record("step_parse", parse_started.elapsed());

    let section = exchange
        .data
        .first()
        .context("STEP file contains no data section")?;

    let table_started = Instant::now();
    let table = Table::from_data_section(section);
    timings.record("step_table", table_started.elapsed());

    if table.shell.is_empty() {
        anyhow::bail!("STEP file contains no shells to tessellate");
    }

    // Resolve the entity graph first. Tolerance is derived from the whole
    // model rather than per shell: a shell-local tolerance meshes a part split
    // into many small shells far finer than the same part as one shell, and a
    // degenerate shell has no extent to scale by at all.
    let mesh_started = Instant::now();
    let shells = table
        .shell
        .par_iter()
        .map(|(id, shell)| {
            table
                .to_compressed_shell(shell)
                .map_err(|error| format!("shell #{id}: {error}"))
        })
        .collect::<Vec<_>>();

    let mut model = BoundingBox::<Point3>::new();
    for shell in shells.iter().flatten() {
        for vertex in &shell.vertices {
            model.push(*vertex);
        }
    }
    let tolerance = model_tolerance(model.diameter());

    // Shells are independent, so tessellation parallelizes cleanly. A shell
    // that fails is reported rather than silently dropped, so a partial render
    // never passes for a complete one.
    let meshed = shells
        .into_par_iter()
        .map(|shell| {
            let shell = shell?;
            // A shell with no surface area carries nothing to render, and
            // feeding it forward only risks degenerate arithmetic downstream.
            if shell.vertices.len() < 3 || shell.faces.is_empty() {
                return Ok(PolygonMesh::default());
            }
            Ok::<PolygonMesh, String>(shell.robust_triangulation(tolerance).to_polygon())
        })
        .collect::<Vec<_>>();
    timings.record("step_tessellate", mesh_started.elapsed());

    let mut positions = Vec::new();
    let mut indices = Vec::new();
    let mut failures = Vec::new();
    for result in meshed {
        match result {
            Ok(polygon) => append_polygon(&polygon, &mut positions, &mut indices),
            Err(error) => failures.push(error),
        }
    }

    if positions.is_empty() {
        anyhow::bail!(
            "STEP tessellation produced no triangles{}",
            describe(&failures)
        );
    }
    if !failures.is_empty() {
        // Loud on stderr rather than a hard failure: a mostly-complete render
        // is useful, but the user must know it is incomplete.
        eprintln!(
            "warning: {} of {} STEP shells failed to tessellate{}",
            failures.len(),
            table.shell.len(),
            describe(&failures)
        );
    }

    Ok((positions, indices))
}

/// Scale the chord tolerance to the model so that a millimetre part and a
/// metre part mesh to comparable density.
///
/// The floor is deliberately well above truck's own 1e-6 minimum. Curves are
/// tessellated in their own parameter space, so a placement scales the
/// tolerance down by its radius before the check happens; sitting exactly on
/// the minimum leaves no headroom and any circle larger than unit radius
/// pushes it under.
fn model_tolerance(diameter: f64) -> f64 {
    let scaled = diameter * RELATIVE_TOLERANCE;
    if scaled.is_finite() && scaled > MIN_TOLERANCE {
        scaled
    } else {
        MIN_TOLERANCE
    }
}

/// Flatten a meshed shell, dropping the per-face indexing in favour of one
/// flat vertex buffer. Triangles are emitted unwelded so that creased edges
/// keep their own normals when the caller generates them.
fn append_polygon(polygon: &PolygonMesh, positions: &mut Vec<[f32; 3]>, indices: &mut Vec<u32>) {
    let vertices = polygon.positions();
    for face in polygon.tri_faces() {
        for vertex in face {
            let point = vertices[vertex.pos];
            indices.push(positions.len() as u32);
            positions.push([point.x as f32, point.y as f32, point.z as f32]);
        }
    }
}

fn describe(failures: &[String]) -> String {
    match failures.first() {
        Some(first) if failures.len() == 1 => format!(": {first}"),
        Some(first) => format!(": {first} (and {} more)", failures.len() - 1),
        None => String::new(),
    }
}
