//! STEP (ISO 10303-21) tessellation.
//!
//! STEP files usually describe solids as boundary representations — trimmed
//! analytic and NURBS surfaces — so there are no triangles to read out. Each
//! shell is evaluated and meshed, then flattened into the same triangle soup
//! the STL path produces, which lets the rest of the pipeline stay unaware of
//! STEP. AP242 also allows a file to ship its mesh directly, which is handled
//! by [`tessellated`].

pub mod part21;
mod tessellated;

use std::time::Instant;

use rayon::prelude::*;
use truck_meshalgo::prelude::*;
use truck_stepio::r#in::Table;

use crate::timing::Timings;

/// Tolerance for a model with no measurable extent, where there is nothing to
/// scale against. Nothing renders from such a shell anyway; this only keeps a
/// degenerate bounding box from producing a zero or non-finite tolerance.
const DEGENERATE_TOLERANCE: f64 = 1.0e-3;

/// Chord deviation as a fraction of a shell's diagonal. Scaling to the model
/// keeps output density stable across files that use different units.
const RELATIVE_TOLERANCE: f64 = 0.001;

/// How many points to sample along each edge when measuring the model.
///
/// Enough to catch the mid-span bulge of a circle or a spline, which is where
/// a vertex-only box loses the most; more would not change the diameter.
const EDGE_SAMPLES: u32 = 4;

/// truck panics below this, and it is not a tolerance we could honour anyway.
///
/// This is not the millimetre-scale floor the comment on [`model_tolerance`]
/// argues against: it is the hard minimum truck's own division asserts on. A
/// model whose measured extent is tiny — or an isolated shell pulled out of a
/// larger assembly — otherwise computes a tolerance below it and aborts.
const MINIMUM_TOLERANCE: f64 = 1.0e-6;

/// Tessellate every shell in a STEP file into one indexed triangle mesh.
///
/// Positions carry no shared topology between faces, so each triangle brings
/// its own vertices and normals are generated by the caller.
pub fn parse_step(
    bytes: &[u8],
    timings: &mut Timings,
) -> anyhow::Result<(Vec<[f32; 3]>, Vec<u32>)> {
    let text = std::str::from_utf8(bytes)
        .map(std::borrow::Cow::Borrowed)
        // STEP is nominally ASCII, but exporters emit Latin-1 in comments and
        // names often enough that rejecting the file would be unhelpful.
        .unwrap_or_else(|_| bytes.iter().map(|&b| b as char).collect::<String>().into());

    let parse_started = Instant::now();
    let mut exchange = read_exchange(&text)?;
    timings.record("step_parse", parse_started.elapsed());

    if exchange.data.is_empty() {
        anyhow::bail!("STEP file contains no data section");
    }
    let section = exchange.data.swap_remove(0);

    // Hand the syntax tree over rather than lending it. The tree is roughly
    // eight times the size of the file and the table another three, so
    // building the table from a borrowed tree keeps both fully resident and
    // makes peak memory, not speed, the limit on how large a model will load.
    let table_started = Instant::now();
    let table = Table::from_owned_data_section(section);
    timings.record("step_table", table_started.elapsed());

    if table.shell.is_empty() {
        // AP242 lets a file ship its mesh directly instead of a boundary
        // representation, in which case there is nothing to evaluate and the
        // triangles are read straight out of the syntax tree. That tree was
        // consumed above, which is the right trade for the boundary
        // representations that are almost every file; these have to read it
        // again. They are rare and small, and parsing is no longer the
        // expensive part of loading one.
        let tessellated_started = Instant::now();
        let reread = read_exchange(&text)?;
        let tessellated = reread.data.first().and_then(tessellated::read);
        timings.record("step_tessellated_read", tessellated_started.elapsed());
        if let Some((positions, indices)) = tessellated {
            return Ok((positions, indices));
        }
        anyhow::bail!("STEP file contains no shells or tessellated faces");
    }

    // Resolve the entity graph first. Tolerance is derived from the whole
    // model rather than per shell: a shell-local tolerance meshes a part split
    // into many small shells far finer than the same part as one shell, and a
    // degenerate shell has no extent to scale by at all.
    let mesh_started = Instant::now();
    let shells = table
        .shell
        .par_iter()
        .map(|(id, shell)| {
            table
                .to_compressed_shell(shell)
                .map_err(|error| format!("shell #{id}: {error}"))
        })
        .collect::<Vec<_>>();

    let mut model = BoundingBox::<Point3>::new();
    for shell in shells.iter().flatten() {
        for vertex in &shell.vertices {
            model.push(*vertex);
        }
        // Vertices alone understate the model, often badly. A full circle
        // carries a single topological vertex, so a disc or a cylinder adds
        // almost nothing to the box while occupying real space: a washer whose
        // three vertices span 0.2 mm measured as 0.2 mm across, and the whole
        // submarine model measured 3.06 against rendered bounds of 7.33.
        // Since the tolerance is a fraction of this diameter, understating it
        // meshes every model finer than asked. Sampling each edge closes the
        // gap for the cost of a few curve evaluations per edge.
        for edge in &shell.edges {
            let (start, end) = edge.curve.range_tuple();
            for step in 0..=EDGE_SAMPLES {
                let t = start + (end - start) * f64::from(step) / f64::from(EDGE_SAMPLES);
                model.push(edge.curve.subs(t));
            }
        }
    }
    let tolerance = model_tolerance(model.diameter());

    // Shells are independent, so tessellation parallelizes cleanly. A shell
    // that fails is reported rather than silently dropped, so a partial render
    // never passes for a complete one.
    let meshed = shells
        .into_par_iter()
        .map(|shell| {
            let shell = shell?;
            // Only a shell with no faces carries nothing to render. Counting
            // *vertices* was wrong: a disc or a cylinder is bounded by full
            // circles, which have one topological vertex each, so this
            // discarded valid solids in silence. A 74-entity washer that OCCT
            // renders fine reached look as "tessellation produced no
            // triangles" for exactly this reason.
            if shell.faces.is_empty() {
                return Ok((PolygonMesh::default(), FaceTally::default()));
            }
            let meshed = shell.robust_triangulation(tolerance);
            // A face that could not be meshed is dropped from the polygon
            // without comment, so count them here while the structure still
            // says which is which. Malformed geometry does reach this: a wire
            // that bounds nothing leaves its face untessellated.
            //
            // There are two ways to lose a face and they do not have the same
            // cause, so they are not summed. `None` is a surface that could not
            // be produced at all, which on real files is mostly a spline
            // failing to converge. `Some` holding no triangles is a surface
            // that meshed to nothing, which happens to *planes* — a separate
            // and unexplained defect. Counting only the first understated the
            // loss on 00009190 by 118 faces, 276 against 394.
            let mut tally = FaceTally {
                total: meshed.faces.len(),
                ..FaceTally::default()
            };
            for face in &meshed.faces {
                match &face.surface {
                    None => tally.unsurfaced += 1,
                    Some(mesh) if mesh.faces().is_empty() => tally.empty += 1,
                    Some(_) => {}
                }
            }
            Ok::<_, String>((meshed.to_polygon(), tally))
        })
        .collect::<Vec<_>>();
    timings.record("step_tessellate", mesh_started.elapsed());

    let mut positions = Vec::new();
    let mut indices = Vec::new();
    let mut failures = Vec::new();
    let mut faces = FaceTally::default();
    for result in meshed {
        match result {
            Ok((polygon, tally)) => {
                append_polygon(&polygon, &mut positions, &mut indices);
                faces.total += tally.total;
                faces.unsurfaced += tally.unsurfaced;
                faces.empty += tally.empty;
            }
            Err(error) => failures.push(error),
        }
    }

    if positions.is_empty() {
        anyhow::bail!(
            "STEP tessellation produced no triangles{}",
            describe(&failures)
        );
    }
    if !failures.is_empty() {
        // Loud on stderr rather than a hard failure: a mostly-complete render
        // is useful, but the user must know it is incomplete.
        eprintln!(
            "warning: {} of {} STEP shells failed to tessellate{}",
            failures.len(),
            table.shell.len(),
            describe(&failures)
        );
    }
    if faces.lost() > 0 {
        // A shell can succeed while individual faces within it do not, and
        // those vanish from the mesh silently. Without this a model missing
        // geometry is indistinguishable from a complete one. The split is
        // reported because it points at which defect to chase.
        eprintln!(
            "warning: {} of {} STEP faces produced no geometry and are missing \
             from the render ({} had no surface, {} meshed to nothing)",
            faces.lost(),
            faces.total,
            faces.unsurfaced,
            faces.empty
        );
    }

    Ok((positions, indices))
}

/// How many faces a shell held, and how many of them yielded no mesh.
///
/// The two loss causes are kept apart because they are different bugs, and a
/// single "dropped" number hid that. See the counting site for which is which.
#[derive(Debug, Default, Clone, Copy)]
struct FaceTally {
    total: usize,
    /// No surface could be produced for the face at all.
    unsurfaced: usize,
    /// A surface was produced, and it meshed to no triangles.
    empty: usize,
}

impl FaceTally {
    /// Faces that reach the render carrying no geometry, however they got there.
    fn lost(&self) -> usize {
        self.unsurfaced + self.empty
    }
}

/// Read the exchange structure.
///
/// [`part21`] reads it far faster than ruststep's nom grammar, but covers a
/// little less of the standard. Whatever it turns down is handed to ruststep,
/// so the fast reader can only add speed and never narrows what look accepts.
fn read_exchange(text: &str) -> anyhow::Result<ruststep::ast::Exchange> {
    match part21::parse(text) {
        Ok(exchange) => Ok(exchange),
        Err(_) => ruststep::parser::parse(text)
            .map_err(|error| anyhow::anyhow!("failed to parse STEP: {error}")),
    }
}

/// Scale the chord tolerance to the model so that a millimetre part and a
/// metre part mesh to comparable density.
///
/// This deliberately has no absolute floor. It used to be held at 1e-3 to stay
/// clear of truck's own 1e-6 minimum, since curves are tessellated in their own
/// parameter space and a placement scales the tolerance down by its radius
/// before that check happens. But an absolute floor silently assumes the file
/// is measured in millimetres. The NIST corpus is, uniformly, so the assumption
/// held there and nowhere else: an Onshape export in metres puts a half
/// millimetre fillet at a radius of 0.0005, well under a 1e-3 floor, which both
/// meshed the part absurdly coarsely and asked truck to approximate a feature
/// to worse than its own size.
///
/// The headroom the floor provided is already in the relative term. Against a
/// radius bounded by the model, `diameter * 1e-3` sits three orders of
/// magnitude above `diameter * 1e-6`, which is the same margin the floor was
/// chosen to give — only expressed in the units the file actually uses.
fn model_tolerance(diameter: f64) -> f64 {
    let scaled = diameter * RELATIVE_TOLERANCE;
    if scaled.is_finite() && scaled > 0.0 {
        scaled.max(MINIMUM_TOLERANCE)
    } else {
        DEGENERATE_TOLERANCE
    }
}

/// Flatten a meshed shell, dropping the per-face indexing in favour of one
/// flat vertex buffer. Triangles are emitted unwelded so that creased edges
/// keep their own normals when the caller generates them.
fn append_polygon(polygon: &PolygonMesh, positions: &mut Vec<[f32; 3]>, indices: &mut Vec<u32>) {
    let vertices = polygon.positions();
    // The triangle count is known, and these buffers reach tens of megabytes
    // on a large assembly. Growing them by doubling holds the old and the new
    // allocation at once at every step, so the high-water mark ends up well
    // above what the mesh actually needs.
    let incoming = polygon.tri_faces().len() * 3;
    positions.reserve(incoming);
    indices.reserve(incoming);
    for face in polygon.tri_faces() {
        for vertex in face {
            let point = vertices[vertex.pos];
            indices.push(positions.len() as u32);
            positions.push([point.x as f32, point.y as f32, point.z as f32]);
        }
    }
}

fn describe(failures: &[String]) -> String {
    match failures.first() {
        Some(first) if failures.len() == 1 => format!(": {first}"),
        Some(first) => format!(": {first} (and {} more)", failures.len() - 1),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A metre-scale export is the case an absolute floor got wrong. Onshape
    /// writes `SI_UNIT($, .METRE.)`, so a part 100 mm across has a diameter of
    /// 0.1 and its half-millimetre fillets have a radius of 0.0005. The old
    /// 1e-3 floor exceeded both the model's own relative tolerance and those
    /// radii, which meshed the part far too coarsely and asked truck to
    /// approximate a sphere to worse than its own size.
    #[test]
    fn a_metre_scale_model_is_not_held_to_a_millimetre_floor() {
        let tolerance = model_tolerance(0.1);
        assert!(
            tolerance < 0.0005,
            "tolerance {tolerance} must stay under a half-millimetre feature"
        );
        assert_eq!(tolerance, 0.1 * RELATIVE_TOLERANCE);
    }

    /// The millimetre-scale corpus this was originally tuned against must mesh
    /// exactly as it did before, since its tolerance was always the scaled term
    /// rather than the floor.
    #[test]
    fn a_millimetre_scale_model_is_unchanged() {
        assert_eq!(model_tolerance(200.0), 0.2);
        assert_eq!(model_tolerance(6.0), 0.006);
    }

    /// Tolerance has to keep tracking the model across every unit a CAD system
    /// might write, rather than flattening onto a constant at small scales.
    #[test]
    fn tolerance_tracks_the_model_across_unit_scales() {
        for diameter in [1.0e-3, 1.0, 1.0e3, 1.0e6] {
            assert_eq!(model_tolerance(diameter), diameter * RELATIVE_TOLERANCE);
        }
    }

    /// A shell with no extent has nothing to scale against, and must not yield
    /// a zero or non-finite tolerance for truck to divide by.
    #[test]
    fn a_degenerate_model_falls_back_to_a_usable_tolerance() {
        for diameter in [0.0, -1.0, f64::NAN, f64::INFINITY] {
            let tolerance = model_tolerance(diameter);
            assert!(
                tolerance.is_finite() && tolerance > 0.0,
                "diameter {diameter} produced tolerance {tolerance}"
            );
        }
    }
}
